export type Player = {
    id: number;
    rank: number;
    name: string;
    ovr: number;
    pac: number;
    sho: number;
    pas: number;
    dri: number;
    def: number;
    phy: number;
    acceleration: number;
    sprintSpeed: number;
    positioning: number;
    finishing: number;
    shotPower: number;
    longShots: number;
    volleys: number;
    penalties: number;
    vision: number;
    crossing: number;
    freeKickAccuracy: number;
    shortPassing: number;
    longPassing: number;
    curve: number;
    dribbling: number;
    agility: number;
    balance: number;
    reactions: number;
    ballControl: number;
    composure: number;
    interceptions: number;
    headingAccuracy: number;
    defAwareness: number;
    standingTackle: number;
    slidingTackle: number;
    jumping: number;
    stamina: number;
    strength: number;
    aggression: number;
    pos: string;
    weakFoot: number;
    skillMoves: number;
    preferredFoot: string;
    height: string;
    weight: string;
    alternativePositions: string;
    age: number;
    nation: string;
    league: string;
    team: string;
    playStyle: string;
    url: string;
    img: string;
    gkDiving: number;
    gkHandling: number;
    gkKicking: number;
    gkPositioning: number;
    gkReflexes: number;
  };

  export type SquadMap = {
    [position: string]: Player[];
  };